/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-03-14 at 19:18:29 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

/**
 * Model definition for AccountingSystem.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class AccountingSystem
{
    /**
     * The value may be {@code null}.
     */

    private String company;

    /**
     * The value may be {@code null}.
     */

    private Boolean disableGZip;

    /**
     * The value may be {@code null}.
     */

    private String password;

    /**
     * The value may be {@code null}.
     */

    private String profile;

    /**
     * The value may be {@code null}.
     */

    private String type;

    /**
     * The value may be {@code null}.
     */

    private String url;

    /**
     * The value may be {@code null}.
     */

    private String username;

    /**
     * @return value or {@code null} for none
     */
    public String getCompany()
    {
        return company;
    }

    /**
     * @param company company or {@code null} for none
     */
    public AccountingSystem setCompany( String company )
    {
        this.company = company;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getDisableGZip()
    {
        return disableGZip;
    }

    /**
     * @param disableGZip disableGZip or {@code null} for none
     */
    public AccountingSystem setDisableGZip( Boolean disableGZip )
    {
        this.disableGZip = disableGZip;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getPassword()
    {
        return password;
    }

    /**
     * @param password password or {@code null} for none
     */
    public AccountingSystem setPassword( String password )
    {
        this.password = password;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getProfile()
    {
        return profile;
    }

    /**
     * @param profile profile or {@code null} for none
     */
    public AccountingSystem setProfile( String profile )
    {
        this.profile = profile;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getType()
    {
        return type;
    }

    /**
     * @param type type or {@code null} for none
     */
    public AccountingSystem setType( String type )
    {
        this.type = type;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getUrl()
    {
        return url;
    }

    /**
     * @param url url or {@code null} for none
     */
    public AccountingSystem setUrl( String url )
    {
        this.url = url;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * @param username username or {@code null} for none
     */
    public AccountingSystem setUsername( String username )
    {
        this.username = username;
        return this;
    }
}
