/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-12-26 at 05:51:20 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

/**
 * Model definition for CreditorContactDetails.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
public final class CreditorContactDetails
{
    /**
     * The value may be {@code null}.
     */
    private String email;

    /**
     * The value may be {@code null}.
     */
    private String name;

    /**
     * The value may be {@code null}.
     */
    private String phone;

    /**
     * The value may be {@code null}.
     */
    private String website;

    /**
     * @return value or {@code null} for none
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * @param email email or {@code null} for none
     */
    public CreditorContactDetails setEmail( String email )
    {
        this.email = email;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getName()
    {
        return name;
    }

    /**
     * @param name name or {@code null} for none
     */
    public CreditorContactDetails setName( String name )
    {
        this.name = name;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getPhone()
    {
        return phone;
    }

    /**
     * @param phone phone or {@code null} for none
     */
    public CreditorContactDetails setPhone( String phone )
    {
        this.phone = phone;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getWebsite()
    {
        return website;
    }

    /**
     * @param website website or {@code null} for none
     */
    public CreditorContactDetails setWebsite( String website )
    {
        this.website = website;
        return this;
    }
}
