/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-03-14 at 19:18:29 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

/**
 * Model definition for Increment.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class Increment
{

    /**
     * The value may be {@code null}.
     */
    
    private String current;

    /**
     * The value may be {@code null}.
     */

    private Long id;

    /**
     * The value may be {@code null}.
     */
    
    private Integer length;

    /**
     * The value may be {@code null}.
     */
    
    private String postfix;

    /**
     * The value may be {@code null}.
     */
    
    private String prefix;

    /**
     * The value may be {@code null}.
     */
    
    private Integer year;

    /**
     * @return value or {@code null} for none
     */
    public String getCurrent()
    {
        return current;
    }

    /**
     * @param current current or {@code null} for none
     */
    public Increment setCurrent( String current )
    {
        this.current = current;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Long getId()
    {
        return id;
    }

    /**
     * @param id id or {@code null} for none
     */
    public Increment setId( Long id )
    {
        this.id = id;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Integer getLength()
    {
        return length;
    }

    /**
     * @param length length or {@code null} for none
     */
    public Increment setLength( Integer length )
    {
        this.length = length;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getPostfix()
    {
        return postfix;
    }

    /**
     * @param postfix postfix or {@code null} for none
     */
    public Increment setPostfix( String postfix )
    {
        this.postfix = postfix;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getPrefix()
    {
        return prefix;
    }

    /**
     * @param prefix prefix or {@code null} for none
     */
    public Increment setPrefix( String prefix )
    {
        this.prefix = prefix;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Integer getYear()
    {
        return year;
    }

    /**
     * @param year year or {@code null} for none
     */
    public Increment setYear( Integer year )
    {
        this.year = year;
        return this;
    }

}
