/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-07-31 at 14:32:05 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

import biz.turnonline.ecosystem.widget.shared.rest.RelevantNullChecker;

import java.util.Date;

/**
 * Model definition for NumberSeries.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class NumberSeries
        implements RelevantNullChecker
{
    /**
     * The value may be {@code null}.
     */
    private String code;

    /**
     * The value may be {@code null}.
     */
    private Increment increment;

    /**
     * The value may be {@code null}.
     */
    private Date modificationDate;

    /**
     * The value may be {@code null}.
     */
    private String symbol;

    /**
     * @return value or {@code null} for none
     */
    public String getCode()
    {
        return code;
    }

    /**
     * @param code code or {@code null} for none
     */
    public NumberSeries setCode( String code )
    {
        this.code = code;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Increment getIncrement()
    {
        return increment;
    }

    /**
     * @param increment increment or {@code null} for none
     */
    public NumberSeries setIncrement( Increment increment )
    {
        this.increment = increment;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Date getModificationDate()
    {
        return modificationDate;
    }

    /**
     * @param modificationDate modificationDate or {@code null} for none
     */
    public NumberSeries setModificationDate( Date modificationDate )
    {
        this.modificationDate = modificationDate;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getSymbol()
    {
        return symbol;
    }

    /**
     * @param symbol symbol or {@code null} for none
     */
    public NumberSeries setSymbol( String symbol )
    {
        this.symbol = symbol;
        return this;
    }

    @Override
    public boolean allNull()
    {
        return allNull( code, increment, symbol );
    }
}
