/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-07-31 at 14:32:05 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

import java.util.List;

/**
 * Model definition for Pricing.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class Pricing
{
    /**
     * The value may be {@code null}.
     */
    private Boolean appliedReverseCharge;

    /**
     * The value may be {@code null}.
     */
    private PricingCustomer customer;

    /**
     * The value may be {@code null}.
     */
    private Boolean discountApplied;

    /**
     * The value may be {@code null}.
     */
    private Boolean discountDefined;

    /**
     * The value may be {@code null}.
     */
    private List<PricingItem> items;

    /**
     * The value may be {@code null}.
     */
    private Double noDiscountTotalPrice;

    /**
     * The value may be {@code null}.
     */
    private Double noDiscountTotalPriceExclVat;

    /**
     * The value may be {@code null}.
     */
    private Double totalPrice;

    /**
     * The value may be {@code null}.
     */
    private Double totalPriceExclVat;

    /**
     * The value may be {@code null}.
     */
    private Double totalVatBase;

    /**
     * @return value or {@code null} for none
     */
    public Boolean getAppliedReverseCharge()
    {
        return appliedReverseCharge;
    }

    /**
     * @param appliedReverseCharge appliedReverseCharge or {@code null} for none
     */
    public Pricing setAppliedReverseCharge( Boolean appliedReverseCharge )
    {
        this.appliedReverseCharge = appliedReverseCharge;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public PricingCustomer getCustomer()
    {
        return customer;
    }

    /**
     * @param customer customer or {@code null} for none
     */
    public Pricing setCustomer( PricingCustomer customer )
    {
        this.customer = customer;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getDiscountApplied()
    {
        return discountApplied;
    }

    /**
     * @param discountApplied discountApplied or {@code null} for none
     */
    public Pricing setDiscountApplied( Boolean discountApplied )
    {
        this.discountApplied = discountApplied;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getDiscountDefined()
    {
        return discountDefined;
    }

    /**
     * @param discountDefined discountDefined or {@code null} for none
     */
    public Pricing setDiscountDefined( Boolean discountDefined )
    {
        this.discountDefined = discountDefined;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public List<PricingItem> getItems()
    {
        return items;
    }

    /**
     * @param items items or {@code null} for none
     */
    public Pricing setItems( List<PricingItem> items )
    {
        this.items = items;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getNoDiscountTotalPrice()
    {
        return noDiscountTotalPrice;
    }

    /**
     * @param noDiscountTotalPrice noDiscountTotalPrice or {@code null} for none
     */
    public Pricing setNoDiscountTotalPrice( Double noDiscountTotalPrice )
    {
        this.noDiscountTotalPrice = noDiscountTotalPrice;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getNoDiscountTotalPriceExclVat()
    {
        return noDiscountTotalPriceExclVat;
    }

    /**
     * @param noDiscountTotalPriceExclVat noDiscountTotalPriceExclVat or {@code null} for none
     */
    public Pricing setNoDiscountTotalPriceExclVat( Double noDiscountTotalPriceExclVat )
    {
        this.noDiscountTotalPriceExclVat = noDiscountTotalPriceExclVat;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getTotalPrice()
    {
        return totalPrice;
    }

    /**
     * @param totalPrice totalPrice or {@code null} for none
     */
    public Pricing setTotalPrice( Double totalPrice )
    {
        this.totalPrice = totalPrice;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getTotalPriceExclVat()
    {
        return totalPriceExclVat;
    }

    /**
     * @param totalPriceExclVat totalPriceExclVat or {@code null} for none
     */
    public Pricing setTotalPriceExclVat( Double totalPriceExclVat )
    {
        this.totalPriceExclVat = totalPriceExclVat;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getTotalVatBase()
    {
        return totalVatBase;
    }

    /**
     * @param totalVatBase totalVatBase or {@code null} for none
     */
    public Pricing setTotalVatBase( Double totalVatBase )
    {
        this.totalVatBase = totalVatBase;
        return this;
    }
}
