/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-09-01 at 18:33:01 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

/**
 * Model definition for ProductOverview.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class ProductOverview
{
    /**
     * The value may be {@code null}.
     */
    private String about;

    /**
     * The value may be {@code null}.
     */
    private String productUrl;

    /**
     * The value may be {@code null}.
     */
    private Boolean published;

    /**
     * The value may be {@code null}.
     */
    private String thumbnailUrl;

    /**
     * @return value or {@code null} for none
     */
    public String getAbout()
    {
        return about;
    }

    /**
     * @param about about or {@code null} for none
     */
    public ProductOverview setAbout( String about )
    {
        this.about = about;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getProductUrl()
    {
        return productUrl;
    }

    /**
     * @param productUrl productUrl or {@code null} for none
     */
    public ProductOverview setProductUrl( String productUrl )
    {
        this.productUrl = productUrl;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getPublished()
    {
        return published;
    }

    /**
     * @param published published or {@code null} for none
     */
    public ProductOverview setPublished( Boolean published )
    {
        this.published = published;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getThumbnailUrl()
    {
        return thumbnailUrl;
    }

    /**
     * @param thumbnailUrl thumbnailUrl or {@code null} for none
     */
    public ProductOverview setThumbnailUrl( String thumbnailUrl )
    {
        this.thumbnailUrl = thumbnailUrl;
        return this;
    }
}
