/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-03-14 at 19:18:29 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.billing;

/**
 * Model definition for ProductDomain.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class ProductDomain
{

    /**
     * The value may be {@code null}.
     */
    
    private String domain;

    /**
     * The value may be {@code null}.
     */
    
    private String name;

    /**
     * The value may be {@code null}.
     */
    
    private String subdomain;

    /**
     * The value may be {@code null}.
     */
    
    private String uri;

    /**
     * The value may be {@code null}.
     */
    
    private String url;

    /**
     * @return value or {@code null} for none
     */
    public String getDomain()
    {
        return domain;
    }

    /**
     * @param domain domain or {@code null} for none
     */
    public ProductDomain setDomain( String domain )
    {
        this.domain = domain;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getName()
    {
        return name;
    }

    /**
     * @param name name or {@code null} for none
     */
    public ProductDomain setName( String name )
    {
        this.name = name;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getSubdomain()
    {
        return subdomain;
    }

    /**
     * @param subdomain subdomain or {@code null} for none
     */
    public ProductDomain setSubdomain( String subdomain )
    {
        this.subdomain = subdomain;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getUri()
    {
        return uri;
    }

    /**
     * @param uri uri or {@code null} for none
     */
    public ProductDomain setUri( String uri )
    {
        this.uri = uri;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getUrl()
    {
        return url;
    }

    /**
     * @param url url or {@code null} for none
     */
    public ProductDomain setUrl( String url )
    {
        this.url = url;
        return this;
    }

}
