/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-03-14 at 19:18:29 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.widget.shared.rest.productbilling;

import java.util.Date;

/**
 * Model definition for ProductPublishing.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Product Billing. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings( "javadoc" )
public final class ProductPublishing
{

    /**
     * The value may be {@code null}.
     */
    
    private ProductDomain at;

    /**
     * The value may be {@code null}.
     */
    
    private Boolean comingSoon;

    /**
     * The value may be {@code null}.
     */
    
    private String description;

    /**
     * The value may be {@code null}.
     */
    
    private Boolean facebookLike;

    /**
     * The value may be {@code null}.
     */
    
    private Boolean googlePlus;

    /**
     * The value may be {@code null}.
     */
    
    private Boolean linkedInShare;

    /**
     * The value may be {@code null}.
     */
    
    private Date modificationDate;

    /**
     * The value may be {@code null}.
     */
    
    private java.util.List<ProductPicture> pictures;

    /**
     * The value may be {@code null}.
     */
    
    private Boolean published;

    /**
     * @return value or {@code null} for none
     */
    public ProductDomain getAt()
    {
        return at;
    }

    /**
     * @param at at or {@code null} for none
     */
    public ProductPublishing setAt( ProductDomain at )
    {
        this.at = at;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getComingSoon()
    {
        return comingSoon;
    }

    /**
     * @param comingSoon comingSoon or {@code null} for none
     */
    public ProductPublishing setComingSoon( Boolean comingSoon )
    {
        this.comingSoon = comingSoon;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * @param description description or {@code null} for none
     */
    public ProductPublishing setDescription( String description )
    {
        this.description = description;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getFacebookLike()
    {
        return facebookLike;
    }

    /**
     * @param facebookLike facebookLike or {@code null} for none
     */
    public ProductPublishing setFacebookLike( Boolean facebookLike )
    {
        this.facebookLike = facebookLike;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getGooglePlus()
    {
        return googlePlus;
    }

    /**
     * @param googlePlus googlePlus or {@code null} for none
     */
    public ProductPublishing setGooglePlus( Boolean googlePlus )
    {
        this.googlePlus = googlePlus;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getLinkedInShare()
    {
        return linkedInShare;
    }

    /**
     * @param linkedInShare linkedInShare or {@code null} for none
     */
    public ProductPublishing setLinkedInShare( Boolean linkedInShare )
    {
        this.linkedInShare = linkedInShare;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Date getModificationDate()
    {
        return modificationDate;
    }

    /**
     * @param modificationDate modificationDate or {@code null} for none
     */
    public ProductPublishing setModificationDate( Date modificationDate )
    {
        this.modificationDate = modificationDate;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.util.List<ProductPicture> getPictures()
    {
        return pictures;
    }

    /**
     * @param pictures pictures or {@code null} for none
     */
    public ProductPublishing setPictures( java.util.List<ProductPicture> pictures )
    {
        this.pictures = pictures;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getPublished()
    {
        return published;
    }

    /**
     * @param published published or {@code null} for none
     */
    public ProductPublishing setPublished( Boolean published )
    {
        this.published = published;
        return this;
    }

}
