/*
 * Billing Processor
 * No description
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package biz.turnonline.ecosystem.widget.shared.rest.bill;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Supplier
 */
public class Supplier
{
    @JsonProperty( "businessName" )
    private String businessName = null;

    @JsonProperty( "companyId" )
    private String companyId = null;

    @JsonProperty( "taxId" )
    private String taxId = null;

    @JsonProperty( "vatId" )
    private String vatId = null;

    @JsonProperty( "firstName" )
    private String firstName = null;

    @JsonProperty( "lastName" )
    private String lastName = null;

    @JsonProperty( "street" )
    private String street = null;

    @JsonProperty( "city" )
    private String city = null;

    @JsonProperty( "country" )
    private String country = null;

    @JsonProperty( "postcode" )
    private String postcode = null;

    @JsonProperty( "prefix" )
    private String prefix = null;

    @JsonProperty( "suffix" )
    private String suffix = null;

    public Supplier businessName( String businessName )
    {
        this.businessName = businessName;
        return this;
    }

    /**
     * Supplier business name.
     *
     * @return businessName
     **/
    @JsonProperty( "businessName" )
    public String getBusinessName()
    {
        return businessName;
    }

    public void setBusinessName( String businessName )
    {
        this.businessName = businessName;
    }

    public Supplier companyId( String companyId )
    {
        this.companyId = companyId;
        return this;
    }

    /**
     * Supplier business identification number.
     *
     * @return companyId
     **/
    @JsonProperty( "companyId" )
    public String getCompanyId()
    {
        return companyId;
    }

    public void setCompanyId( String companyId )
    {
        this.companyId = companyId;
    }

    public Supplier taxId( String taxId )
    {
        this.taxId = taxId;
        return this;
    }

    /**
     * Supplier tax payer identification number.
     *
     * @return taxId
     **/
    @JsonProperty( "taxId" )
    public String getTaxId()
    {
        return taxId;
    }

    public void setTaxId( String taxId )
    {
        this.taxId = taxId;
    }

    public Supplier vatId( String vatId )
    {
        this.vatId = vatId;
        return this;
    }

    /**
     * Supplier vat payer identification number.
     *
     * @return vatId
     **/
    @JsonProperty( "vatId" )
    public String getVatId()
    {
        return vatId;
    }

    public void setVatId( String vatId )
    {
        this.vatId = vatId;
    }

    public Supplier firstName( String firstName )
    {
        this.firstName = firstName;
        return this;
    }

    /**
     * The personal first name.
     *
     * @return firstName
     **/
    @JsonProperty( "firstName" )
    public String getFirstName()
    {
        return firstName;
    }

    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }

    public Supplier lastName( String lastName )
    {
        this.lastName = lastName;
        return this;
    }

    /**
     * The personal last name.
     *
     * @return lastName
     **/
    @JsonProperty( "lastName" )
    public String getLastName()
    {
        return lastName;
    }

    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }

    public Supplier street( String street )
    {
        this.street = street;
        return this;
    }

    /**
     * The street and street number.
     *
     * @return street
     **/
    @JsonProperty( "street" )
    public String getStreet()
    {
        return street;
    }

    public void setStreet( String street )
    {
        this.street = street;
    }

    public Supplier city( String city )
    {
        this.city = city;
        return this;
    }

    /**
     * The address city.
     *
     * @return city
     **/
    @JsonProperty( "city" )
    public String getCity()
    {
        return city;
    }

    public void setCity( String city )
    {
        this.city = city;
    }

    public Supplier country( String country )
    {
        this.country = country;
        return this;
    }

    /**
     * The address ISO 3166 alpha-2 country code. It’s case insensitive.
     *
     * @return country
     **/
    @JsonProperty( "country" )
    public String getCountry()
    {
        return country;
    }

    public void setCountry( String country )
    {
        this.country = country;
    }

    public Supplier postcode( String postcode )
    {
        this.postcode = postcode;
        return this;
    }

    /**
     * The address post code.
     *
     * @return postcode
     **/
    @JsonProperty( "postcode" )
    public String getPostcode()
    {
        return postcode;
    }

    public void setPostcode( String postcode )
    {
        this.postcode = postcode;
    }

    public Supplier prefix( String prefix )
    {
        this.prefix = prefix;
        return this;
    }

    /**
     * The personal name prefix.
     *
     * @return prefix
     **/
    @JsonProperty( "prefix" )
    public String getPrefix()
    {
        return prefix;
    }

    public void setPrefix( String prefix )
    {
        this.prefix = prefix;
    }

    public Supplier suffix( String suffix )
    {
        this.suffix = suffix;
        return this;
    }

    /**
     * The personal name suffix.
     *
     * @return suffix
     **/
    @JsonProperty( "suffix" )
    public String getSuffix()
    {
        return suffix;
    }

    public void setSuffix( String suffix )
    {
        this.suffix = suffix;
    }

    @Override
    public String toString()
    {
        return "class Supplier {\n" +
                "    businessName: " + toIndentedString( businessName ) + "\n" +
                "    companyId: " + toIndentedString( companyId ) + "\n" +
                "    taxId: " + toIndentedString( taxId ) + "\n" +
                "    vatId: " + toIndentedString( vatId ) + "\n" +
                "    firstName: " + toIndentedString( firstName ) + "\n" +
                "    lastName: " + toIndentedString( lastName ) + "\n" +
                "    street: " + toIndentedString( street ) + "\n" +
                "    city: " + toIndentedString( city ) + "\n" +
                "    country: " + toIndentedString( country ) + "\n" +
                "    postcode: " + toIndentedString( postcode ) + "\n" +
                "    prefix: " + toIndentedString( prefix ) + "\n" +
                "    suffix: " + toIndentedString( suffix ) + "\n" +
                "}";
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}

